require('dotenv').config();
const { getDb, run, waitForDb } = require('./src/db/database');
const { v4: uuidv4 } = require('uuid');

async function seed() {
  await getDb();

  // Clear all
  run('DELETE FROM answers');
  run('DELETE FROM writing_submissions');
  run('DELETE FROM exam_attempts');
  run('DELETE FROM questions');
  run('DELETE FROM question_groups');
  run('DELETE FROM passages');

  console.log('🌱 Seeding...\n');

  function addPassage(section, title, body, order, audioUrl = null) {
    const id = uuidv4();
    run('INSERT INTO passages (id, section, title, body, audio_url, order_index) VALUES (?, ?, ?, ?, ?, ?)',
      [id, section, title, body || null, audioUrl, order]);
    return id;
  }

  function addGroup(passageId, type, instruction, from, to, order) {
    const id = uuidv4();
    run(`INSERT INTO question_groups (id, passage_id, question_type, instruction, from_number, to_number, order_index)
         VALUES (?, ?, ?, ?, ?, ?, ?)`,
      [id, passageId, type, instruction, from, to, order]);
    return id;
  }

  function addQuestion(groupId, number, text, options, answer) {
    run(`INSERT INTO questions (id, group_id, question_number, question_text, options, correct_answer)
         VALUES (?, ?, ?, ?, ?, ?)`,
      [uuidv4(), groupId, number, text,
        options ? JSON.stringify(options) : null,
        answer || null]);
  }

  const TF = ['True', 'False', 'Not Given'];

  // ══════════════════════════════════════════════
  // READING PASSAGE 1 — Electroreception
  // ══════════════════════════════════════════════
  const rp1 = addPassage('reading', 'Electroreception in Animals', `A. Open your eyes in sea water and it is difficult to see much more than a murky, bleary green colour. The same holds for almost all aquatic environments — rivers, lakes, and oceans are optically hostile places for creatures that evolved on land. Yet many fish, sharks, and rays navigate, hunt, and communicate with extraordinary precision in these conditions. The secret lies not in superior eyesight, but in a remarkable ability to detect electrical fields — a sense known as electroreception.

B. Electroreception comes in two variants. While all animals (including humans) generate electric signals as a by-product of nerve and muscle activity, only certain creatures have evolved specialised organs to detect those of others. Passive electroreception simply detects ambient electrical fields produced by other organisms. Active electroreception goes further: the animal generates its own electric field and senses distortions in it caused by nearby objects — in effect, an electric sense of touch at a distance.

C. The best-known electroreceptive animal is the shark. Its snout is dotted with jelly-filled pores called the ampullae of Lorenzini, which can detect electrical fields as faint as five billionths of a volt per centimetre. This exquisite sensitivity allows sharks to detect the bioelectric signatures of prey buried under sand, and may also help them navigate using the Earth's magnetic field.

D. Why is electroreception so rare among land animals? The answer lies in physics. Air is a very poor electrical conductor, so the fields generated by living creatures dissipate almost immediately. Water, by contrast, conducts electricity well, allowing signals to travel several metres. Electroreception therefore only offers a survival advantage in aquatic or semi-aquatic environments.

E. Researchers have speculated that migratory fish could use electroreception to sense the weak electrical fields generated by ocean currents moving through the Earth's magnetic field. If so, electroreception may function as a biological compass for long-distance navigation — a hypothesis supported by the observation that sharks often follow precise magnetic headings across open ocean.

F. Weakly electric fish face a further challenge: when many individuals are present in the same stretch of river, their discharges can interfere with each other. Some species avoid this problem by shifting the frequency of their electric organ discharge when they detect a neighbour operating at a similar frequency — a behaviour known as the jamming avoidance response.

G. The practical applications of electroreception research are only beginning to be explored. Engineers have drawn inspiration from the ampullae of Lorenzini to develop highly sensitive underwater sensors capable of detecting submarines and pipelines. Biomedical researchers are investigating whether similar principles could detect the electrical activity of tumours.`, 1);

  // Group 1: Paragraph matching Q1–7
  const rp1g1 = addGroup(rp1, 'matching',
    'Reading Passage 1 has seven paragraphs, A–G. Which paragraph contains the following information? Write the correct letter A–G in boxes 1–7 on your answer sheet. NB You may use any letter more than once.',
    1, 7, 1);
  addQuestion(rp1g1, 1, 'A general introduction explaining why underwater vision is limited', null, 'A');
  addQuestion(rp1g1, 2, 'A description of the two types of electroreception', null, 'B');
  addQuestion(rp1g1, 3, 'The specific organ sharks use to detect electrical fields', null, 'C');
  addQuestion(rp1g1, 4, 'Why land animals cannot use electroreception', null, 'D');
  addQuestion(rp1g1, 5, 'How electroreception may help animals navigate across long distances', null, 'E');
  addQuestion(rp1g1, 6, 'How some fish avoid disrupting each other\'s electrical signals', null, 'F');
  addQuestion(rp1g1, 7, 'Practical human applications inspired by electroreception research', null, 'G');

  // Group 2: True/False/Not Given Q8–13
  const rp1g2 = addGroup(rp1, 'true_false',
    'Do the following statements agree with the information given in Reading Passage 1? In boxes 8–13 write TRUE if the statement agrees with the information, FALSE if the statement contradicts the information, or NOT GIVEN if there is no information on this.',
    8, 13, 2);
  addQuestion(rp1g2, 8, 'All animals have evolved specialised organs to detect electrical fields.', TF, 'False');
  addQuestion(rp1g2, 9, 'Sharks can detect prey that is hidden beneath sand.', TF, 'True');
  addQuestion(rp1g2, 10, 'The ampullae of Lorenzini can detect fields as faint as five billionths of a volt per centimetre.', TF, 'True');
  addQuestion(rp1g2, 11, 'Land animals lost electroreception because they evolved in dry climates.', TF, 'Not Given');
  addQuestion(rp1g2, 12, 'Some migratory fish use electroreception as a navigational compass.', TF, 'True');
  addQuestion(rp1g2, 13, 'The jamming avoidance response has been observed in sharks.', TF, 'False');

  // Group 3: Fill in blank Q14–17
  const rp1g3 = addGroup(rp1, 'fill_blank',
    'Complete the sentences below. Choose NO MORE THAN TWO WORDS from the passage for each answer. Write your answers in boxes 14–17 on your answer sheet.',
    14, 17, 3);
  addQuestion(rp1g3, 14, 'Shark snouts contain jelly-filled pores called the ________.', null, 'ampullae of Lorenzini');
  addQuestion(rp1g3, 15, 'An animal that generates its own electric field uses ________ electroreception.', null, 'active');
  addQuestion(rp1g3, 16, 'The behaviour where fish shift discharge frequency to avoid interference is the ________.', null, 'jamming avoidance response');
  addQuestion(rp1g3, 17, 'Engineers have used electroreception research to develop sensors that detect ________ underwater.', null, 'submarines');

  // Group 4: MCQ Q18–20
  const rp1g4 = addGroup(rp1, 'mcq',
    'Choose the correct letter A, B, C or D. Write the correct letter in boxes 18–20 on your answer sheet.',
    18, 20, 4);
  addQuestion(rp1g4, 18, 'What is the main purpose of Paragraph G?',
    ['A. To criticise current technology', 'B. To describe future research challenges', 'C. To show real-world uses of electroreception research', 'D. To explain how sharks navigate'], 'C');
  addQuestion(rp1g4, 19, 'According to the passage, why does water allow electroreception to work?',
    ['A. It amplifies electrical signals', 'B. It is a good electrical conductor', 'C. It blocks competing signals', 'D. It is transparent to electrical fields'], 'B');
  addQuestion(rp1g4, 20, 'What does the jamming avoidance response suggest about electroreception?',
    ['A. It is only found in sharks', 'B. It is a form of passive electroreception', 'C. It is used for communication between individuals', 'D. It was recently discovered by researchers'], 'C');

  console.log('✅ Reading Passage 1 — Electroreception (Q1–20)');

  // ══════════════════════════════════════════════
  // READING PASSAGE 2 — Urban Farming
  // ══════════════════════════════════════════════
  const rp2 = addPassage('reading', 'The Rise of Urban Farming', `A. For most of human history, the idea of growing food inside a city would have seemed absurd. Farmland existed beyond city walls; urban space was reserved for commerce, housing, and industry. Yet today, from rooftop gardens in New York to vertical farms in Singapore, cities around the world are reclaiming agricultural production. Urban farming is increasingly seen as a serious response to the pressures of a rapidly urbanising world.

B. The appeal of urban farming is easy to understand. As cities expand and global supply chains become more vulnerable to disruption — whether from extreme weather, geopolitical tensions, or pandemics — the idea of producing food close to where it is consumed becomes increasingly attractive. Urban farms reduce transport distances, cut carbon emissions, and can deliver fresher produce. Advocates also point to social benefits: community gardens have been shown to reduce social isolation and improve mental health.

C. Technology has been a key enabler. Advances in LED lighting, hydroponics, and climate control have made it possible to grow crops in environments where traditional agriculture would be impossible. Vertical farms — multi-storey facilities where crops are grown in stacked layers under artificial light — can produce yields per square metre many times higher than conventional field farming. Some operations claim to use up to 95% less water than traditional methods.

D. Critics, however, raise important questions. The energy demands of indoor vertical farming are substantial: artificial lighting and climate control systems consume large quantities of electricity, and unless that electricity comes from renewable sources, the carbon footprint of a vertically farmed lettuce may exceed that of one grown in a field. Many urban farming ventures have struggled to turn a profit, relying on subsidies or premium pricing that places their produce out of reach for lower-income consumers.

E. Despite these challenges, the sector continues to attract significant investment. Governments in Japan, the Netherlands, and the United Arab Emirates have made urban agriculture a component of national food security strategies. In Japan, more than 200 plant factories now operate commercially, producing salad greens, herbs, and strawberries year-round. Singapore has set a target to produce 30% of its nutritional needs locally by 2030.

F. The future of urban farming likely lies not in replacing conventional agriculture but in complementing it. High-value, perishable crops such as leafy greens, herbs, and berries are well suited to urban production. Staple crops such as wheat, rice, and maize are not. A realistic vision may involve a patchwork of production methods: rural fields for bulk commodities and urban farms for fresh produce.

G. Urban farming also raises questions about land ownership and access. In many cities, land best suited to urban agriculture is controlled by private developers for whom food production is rarely the highest-value use. Advocates argue that city planners must treat food-growing space as essential urban infrastructure, in the same way they treat parks and transport links.`, 2);

  // Group 1: Paragraph matching Q21–27
  const rp2g1 = addGroup(rp2, 'matching',
    'Reading Passage 2 has seven paragraphs, A–G. Which paragraph contains the following information? Write the correct letter A–G in boxes 21–27 on your answer sheet.',
    21, 27, 1);
  addQuestion(rp2g1, 21, 'The historical separation between city life and food production', null, 'A');
  addQuestion(rp2g1, 22, 'The environmental and social benefits claimed for urban farming', null, 'B');
  addQuestion(rp2g1, 23, 'How new technology has made urban farming more productive', null, 'C');
  addQuestion(rp2g1, 24, 'Concerns about energy use and economic sustainability', null, 'D');
  addQuestion(rp2g1, 25, 'Government policies supporting urban agriculture as a strategic priority', null, 'E');
  addQuestion(rp2g1, 26, 'A prediction about how urban and rural farming might coexist in future', null, 'F');
  addQuestion(rp2g1, 27, 'Questions about who controls land suitable for urban farming', null, 'G');

  // Group 2: True/False/Not Given Q28–33
  const rp2g2 = addGroup(rp2, 'true_false',
    'Do the following statements agree with the information given in Reading Passage 2? In boxes 28–33 write TRUE, FALSE, or NOT GIVEN.',
    28, 33, 2);
  addQuestion(rp2g2, 28, 'Vertical farms consistently use less water than conventional farming.', TF, 'True');
  addQuestion(rp2g2, 29, 'Community gardens have been proven to reduce crime rates in cities.', TF, 'Not Given');
  addQuestion(rp2g2, 30, 'Singapore currently produces 30% of its own food.', TF, 'False');
  addQuestion(rp2g2, 31, 'Many urban farming businesses have struggled to make a profit.', TF, 'True');
  addQuestion(rp2g2, 32, 'Japan has more than 200 plant factories operating commercially.', TF, 'True');
  addQuestion(rp2g2, 33, 'The author argues that urban farming should completely replace rural farming.', TF, 'False');

  // Group 3: Fill in blank Q34–37
  const rp2g3 = addGroup(rp2, 'fill_blank',
    'Complete the sentences below. Choose NO MORE THAN TWO WORDS from the passage for each answer. Write your answers in boxes 34–37 on your answer sheet.',
    34, 37, 3);
  addQuestion(rp2g3, 34, 'Crops grown in stacked layers under artificial light are produced in ________ farms.', null, 'vertical');
  addQuestion(rp2g3, 35, 'Urban farming is especially suitable for high-value ________ crops such as leafy greens.', null, 'perishable');
  addQuestion(rp2g3, 36, 'Japan has more than 200 ________ operating commercially year-round.', null, 'plant factories');
  addQuestion(rp2g3, 37, 'City planners should treat food-growing space as essential urban ________.', null, 'infrastructure');

  // Group 4: MCQ Q38–40
  const rp2g4 = addGroup(rp2, 'mcq',
    'Choose the correct letter A, B, C or D. Write the correct letter in boxes 38–40 on your answer sheet.',
    38, 40, 4);
  addQuestion(rp2g4, 38, 'What is the main argument of Paragraph D?',
    ['A. Urban farming is always environmentally harmful', 'B. Urban farming has significant unresolved drawbacks', 'C. Urban farms are too expensive to build', 'D. Renewable energy makes urban farming viable'], 'B');
  addQuestion(rp2g4, 39, 'According to the passage, which crops are NOT well suited to urban farming?',
    ['A. Leafy greens', 'B. Herbs', 'C. Wheat and rice', 'D. Strawberries'], 'C');
  addQuestion(rp2g4, 40, 'What does the author suggest city planners should do?',
    ['A. Ban private developers from city centres', 'B. Treat food-growing space as essential infrastructure', 'C. Prioritise rooftop solar panels over gardens', 'D. Limit urban farming to residential areas'], 'B');

  console.log('✅ Reading Passage 2 — Urban Farming (Q21–40)');

  // ══════════════════════════════════════════════
  // LISTENING SECTION 1 — Accommodation Office
  // ══════════════════════════════════════════════
  const lp1 = addPassage('listening', 'Campus Accommodation Office — Conversation', `[Section 1 — A conversation between a student and a university accommodation officer]

Officer: Good morning, Accommodation Services. How can I help you?
Student: Hi, I'm calling about my room booking for next semester. My name is James Thornton. I'm a second-year student, student number 4471892.
Officer: Let me pull up your record. You're currently in Riverside Hall, room 14B. What seems to be the problem?
Student: I requested a single room with a shared kitchen, but the confirmation I received shows a shared room. I need a single because I work late at night on my dissertation.
Officer: I completely understand. We do have single rooms in Meadow Block — about a five-minute walk from the main library.
Student: That sounds perfect. Is there a price difference?
Officer: Yes, the single room in Meadow Block is £95 per week, compared to the shared room at £72. The single includes a small private study desk and en-suite bathroom.
Student: That's fine. I receive a bursary that covers accommodation.
Officer: Great. I'll need you to come in to sign the updated contract. We're open Monday to Friday, 9am to 5pm, and on Saturday mornings until midday.
Student: Can I come in this Thursday at around 3pm?
Officer: Thursday is fine. Bring your student ID and your bursary confirmation letter. The new room will be available from the 15th of next month.
Student: Does Meadow Block have a laundry room?
Officer: Yes, on the ground floor. It's coin-operated — £2 per wash and £1.50 to dry. There are also bicycle storage facilities next to the entrance.
Student: Wonderful. Thank you very much.`, 1, '/uploads/listening/ielts-listening-test.wav');

  // Group 1: Fill in blank Q1–8
  const lp1g1 = addGroup(lp1, 'fill_blank',
    'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer. Write your answers in boxes 1–8 on your answer sheet.',
    1, 8, 1);
  addQuestion(lp1g1, 1, 'Student\'s last name: ________', null, 'Thornton');
  addQuestion(lp1g1, 2, 'Student number: ________', null, '4471892');
  addQuestion(lp1g1, 3, 'Current hall: ________ Hall', null, 'Riverside');
  addQuestion(lp1g1, 4, 'New single room location: ________ Block', null, 'Meadow');
  addQuestion(lp1g1, 5, 'Cost of single room: £________ per week', null, '95');
  addQuestion(lp1g1, 6, 'Cost of shared room: £________ per week', null, '72');
  addQuestion(lp1g1, 7, 'Appointment day: ________', null, 'Thursday');
  addQuestion(lp1g1, 8, 'New room available from the ________ of next month', null, '15th');

  // Group 2: MCQ Q9–14
  const lp1g2 = addGroup(lp1, 'mcq',
    'Choose the correct letter A, B or C. Write the correct letter in boxes 9–14 on your answer sheet.',
    9, 14, 2);
  addQuestion(lp1g2, 9, 'Why does the student need a single room?',
    ['A. He has a roommate who disturbs him', 'B. He works late at night on his dissertation', 'C. His bursary requires a single room'], 'B');
  addQuestion(lp1g2, 10, 'What does the single room include?',
    ['A. Private kitchen and living room', 'B. Study desk and en-suite bathroom', 'C. Balcony and storage unit'], 'B');
  addQuestion(lp1g2, 11, 'What must the student bring to the office?',
    ['A. Student ID and bank statement', 'B. Passport and acceptance letter', 'C. Student ID and bursary confirmation letter'], 'C');
  addQuestion(lp1g2, 12, 'How much does the washing machine cost?',
    ['A. £1.50', 'B. £2.00', 'C. £2.50'], 'B');
  addQuestion(lp1g2, 13, 'What facility is next to the entrance of Meadow Block?',
    ['A. Car park', 'B. Post office', 'C. Bicycle storage'], 'C');
  addQuestion(lp1g2, 14, 'What are the Saturday opening hours?',
    ['A. 9am to 5pm', 'B. 9am to midday', 'C. 10am to 4pm'], 'B');

  // Group 3: True/False/Not Given Q15–20
  const lp1g3 = addGroup(lp1, 'true_false',
    'Do the following statements agree with the information in the listening? Write TRUE, FALSE, or NOT GIVEN in boxes 15–20 on your answer sheet.',
    15, 20, 3);
  addQuestion(lp1g3, 15, 'The student is a first-year student.', TF, 'False');
  addQuestion(lp1g3, 16, 'Meadow Block is a five-minute walk from the main library.', TF, 'True');
  addQuestion(lp1g3, 17, 'The laundry room is on the first floor of Meadow Block.', TF, 'False');
  addQuestion(lp1g3, 18, 'The student\'s bursary covers accommodation costs.', TF, 'True');
  addQuestion(lp1g3, 19, 'The accommodation office is open seven days a week.', TF, 'False');
  addQuestion(lp1g3, 20, 'The drying cycle costs less than the washing cycle.', TF, 'True');

  console.log('✅ Listening Section 1 — Accommodation Office (Q1–20)');

  // ══════════════════════════════════════════════
  // LISTENING SECTION 2 — Psychology Lecture
  // ══════════════════════════════════════════════
  const lp2 = addPassage('listening', 'University Lecture — The Psychology of Decision Making', `[Section 4 — A university lecture on behavioural economics]

Today I want to talk about one of the most counterintuitive findings in modern psychology: the idea that having more choices can actually make us less happy and less decisive. This phenomenon is known as the paradox of choice, popularised by American psychologist Barry Schwartz in his 2004 book of the same name.

Schwartz drew on a now-famous study conducted by Sheena Iyengar and Mark Lepper at a supermarket in California. On one day, shoppers encountered a display of 24 varieties of jam. On another day, the same display offered only 6 varieties. The display with 24 jams attracted more browsers, but the display with only 6 jams resulted in ten times more purchases.

The psychological mechanism behind this is what researchers call decision fatigue. Every time we make a choice, we consume a small amount of mental energy. When faced with many options, we exhaust this resource before reaching a decision. This is why judges give harsher sentences later in the day, and why some highly productive individuals — famously Barack Obama and Mark Zuckerberg — deliberately limit their daily wardrobe choices.

A related concept is the distinction between maximisers and satisficers. A maximiser seeks the objectively best option — reading every review, comparing every price, delaying a decision until certain of the optimum. A satisficer sets a threshold of acceptability and chooses the first option that meets it. Research consistently shows that satisficers report higher levels of life satisfaction and lower levels of regret.

The practical implications are significant. Retailers are redesigning stores to reduce option overload. Healthcare providers are simplifying treatment menus. Governments are using choice architecture — the deliberate design of decision environments — to nudge citizens toward better outcomes in areas ranging from pension savings to organ donation.`, 2, '/uploads/listening/ielts-listening-test.wav');

  // Group 1: Fill in blank Q21–27
  const lp2g1 = addGroup(lp2, 'fill_blank',
    'Complete the summary below. Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer. Write your answers in boxes 21–27 on your answer sheet.',
    21, 27, 1);
  addQuestion(lp2g1, 21, 'The paradox of choice was popularised by ________ in 2004.', null, 'Barry Schwartz');
  addQuestion(lp2g1, 22, 'The jam study was conducted by Sheena Iyengar and ________.', null, 'Mark Lepper');
  addQuestion(lp2g1, 23, 'The display with ________ jams resulted in ten times more purchases.', null, '6');
  addQuestion(lp2g1, 24, 'The mental exhaustion from too many choices is called ________ fatigue.', null, 'decision');
  addQuestion(lp2g1, 25, 'Someone who seeks the best possible option is called a ________.', null, 'maximiser');
  addQuestion(lp2g1, 26, 'Someone who picks the first acceptable option is called a ________.', null, 'satisficer');
  addQuestion(lp2g1, 27, 'The deliberate design of decision environments is called choice ________.', null, 'architecture');

  // Group 2: MCQ Q28–34
  const lp2g2 = addGroup(lp2, 'mcq',
    'Choose the correct letter A, B or C. Write the correct letter in boxes 28–34 on your answer sheet.',
    28, 34, 2);
  addQuestion(lp2g2, 28, 'What was the key finding of the jam study?',
    ['A. More variety increases customer satisfaction', 'B. Fewer options leads to more purchases', 'C. Supermarkets should stock more products'], 'B');
  addQuestion(lp2g2, 29, 'Why do judges give harsher sentences later in the day?',
    ['A. They are under more pressure', 'B. They have used up mental energy making decisions', 'C. They work with more difficult cases in the afternoon'], 'B');
  addQuestion(lp2g2, 30, 'Why do some productive people limit their wardrobe choices?',
    ['A. To save money', 'B. To improve their public image', 'C. To eliminate unnecessary decisions'], 'C');
  addQuestion(lp2g2, 31, 'Compared to maximisers, satisficers tend to report:',
    ['A. More regret but better outcomes', 'B. Higher life satisfaction and lower regret', 'C. More stress but fewer mistakes'], 'B');
  addQuestion(lp2g2, 32, 'Where was the jam study conducted?',
    ['A. A supermarket in the United Kingdom', 'B. A supermarket in California', 'C. A shopping mall in New York'], 'B');
  addQuestion(lp2g2, 33, 'What is the main topic of this lecture?',
    ['A. How supermarkets influence spending', 'B. Why maximisers earn more money', 'C. The relationship between choice and happiness'], 'C');
  addQuestion(lp2g2, 34, 'What was the display with 24 jams better at than the display with 6?',
    ['A. Generating sales', 'B. Attracting browsers', 'C. Building brand loyalty'], 'B');

  // Group 3: True/False/Not Given Q35–40
  const lp2g3 = addGroup(lp2, 'true_false',
    'Do the following statements agree with the information in the listening? Write TRUE, FALSE, or NOT GIVEN in boxes 35–40 on your answer sheet.',
    35, 40, 3);
  addQuestion(lp2g3, 35, 'Barry Schwartz published his book on the paradox of choice in 2004.', TF, 'True');
  addQuestion(lp2g3, 36, 'The jam study was conducted in a supermarket in the United Kingdom.', TF, 'False');
  addQuestion(lp2g3, 37, 'Barack Obama is mentioned as someone who limits daily decisions.', TF, 'True');
  addQuestion(lp2g3, 38, 'Satisficers always make objectively better choices than maximisers.', TF, 'False');
  addQuestion(lp2g3, 39, 'Retailers are redesigning stores in response to research on choice overload.', TF, 'True');
  addQuestion(lp2g3, 40, 'The lecture mentions a study on the effects of choice on children.', TF, 'Not Given');

  console.log('✅ Listening Section 2 — Psychology Lecture (Q21–40)');

  // ══════════════════════════════════════════════
  // WRITING — 2 questions
  // ══════════════════════════════════════════════
  const wp1 = addPassage('writing', 'IELTS Writing Task 1 — Bar Chart', null, 1);
  const wp1g1 = addGroup(wp1, 'essay',
    'You should spend about 20 minutes on this task. The bar chart below shows the percentage of people in four countries (UK, Germany, Japan, and Brazil) who used online banking across three age groups (18–30, 31–50, and 51+) in 2022. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.',
    1, 1, 1);
  addQuestion(wp1g1, 1, 'Write your Task 1 report below.', null, null);

  const wp2 = addPassage('writing', 'IELTS Writing Task 2 — Discussion Essay', null, 2);
  const wp2g1 = addGroup(wp2, 'essay',
    'You should spend about 40 minutes on this task. Some people believe that universities should focus exclusively on providing academic knowledge, while others argue that universities should also prepare students for employment by offering practical skills training. Discuss both views and give your own opinion. Give reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words.',
    1, 1, 1);
  addQuestion(wp2g1, 1, 'Write your Task 2 essay below.', null, null);

  console.log('✅ Writing — 2 questions (Task 1 + Task 2)');

  // ══════════════════════════════════════════════
  // SPEAKING — 3 parts
  // ══════════════════════════════════════════════
  const sp1 = addPassage('speaking', 'IELTS Speaking Part 1 — Introduction & Interview', null, 1);
  const sp1g1 = addGroup(sp1, 'speaking_prompt',
    'Part 1 — Introduction & Interview (4–5 minutes). The examiner will ask you general questions about yourself and familiar topics. Answer each question naturally in 2–3 sentences.',
    1, 4, 1);
  addQuestion(sp1g1, 1, 'Where are you from, and what do you like most about living there?', null, null);
  addQuestion(sp1g1, 2, 'Do you currently work or study? Tell me about it.', null, null);
  addQuestion(sp1g1, 3, 'What do you enjoy doing in your free time?', null, null);
  addQuestion(sp1g1, 4, 'How important is technology in your daily life?', null, null);

  const sp2 = addPassage('speaking', 'IELTS Speaking Part 2 — Individual Long Turn', null, 2);
  const sp2g1 = addGroup(sp2, 'speaking_prompt',
    'Part 2 — Individual Long Turn (3–4 minutes). Read the task card below. You have 1 minute to prepare your answer. Then speak for 1–2 minutes.',
    1, 1, 1);
  addQuestion(sp2g1, 1, 'Describe a skill you have learned that you consider useful in everyday life. You should say: what the skill is / how and when you learned it / how often you use it / and explain why you consider it useful in everyday life.', null, null);

  const sp3 = addPassage('speaking', 'IELTS Speaking Part 3 — Two-way Discussion', null, 3);
  const sp3g1 = addGroup(sp3, 'speaking_prompt',
    'Part 3 — Two-way Discussion (4–5 minutes). The examiner will ask you abstract questions related to the topic in Part 2. Develop your answers fully with reasons and examples.',
    1, 3, 1);
  addQuestion(sp3g1, 1, 'Why do you think some people find it difficult to learn new skills as adults compared to children?', null, null);
  addQuestion(sp3g1, 2, 'How has technology changed the way people learn new skills today?', null, null);
  addQuestion(sp3g1, 3, 'Do you think schools prepare students well enough for the practical skills needed in adult life? Why or why not?', null, null);

  console.log('✅ Speaking — 3 parts (Parts 1, 2 & 3)');

  console.log('\n🎉 All done!');
  console.log('   📖 Reading:   40 questions across 2 passages');
  console.log('   🎧 Listening: 40 questions across 2 sections');
  console.log('   ✍️  Writing:    2 tasks');
  console.log('   🗣️  Speaking:   3 parts');
  await waitForDb();
  process.exit(0);
}

seed().catch(err => {
  console.error('❌ Seed failed:', err.message);
  process.exit(1);
});
